# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mutate_deleq <- function(mat, boxbounds, fParam) {
    .Call('_pdutils_mutate_deleq', PACKAGE = 'pdutils', mat, boxbounds, fParam)
}

project_population <- function(mat, Emat, constr) {
    .Call('_pdutils_project_population', PACKAGE = 'pdutils', mat, Emat, constr)
}

gen_init_pop <- function(NP, boxbounds, Emat, constr) {
    .Call('_pdutils_gen_init_pop', PACKAGE = 'pdutils', NP, boxbounds, Emat, constr)
}

gen_init_pop_x0 <- function(NP, boxbounds, Emat, constr, x0) {
    .Call('_pdutils_gen_init_pop_x0', PACKAGE = 'pdutils', NP, boxbounds, Emat, constr, x0)
}

pt_multi_pd <- function(nums, defs, rho, tau, pers, ci, simulations) {
    .Call('_pdutils_pt_multi_pd', PACKAGE = 'pdutils', nums, defs, rho, tau, pers, ci, simulations)
}

